name: CD

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-deploy-${{ inputs.environment }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: "Setup"

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    outputs:
      matrix: ${{ steps.matrix.outputs.value }}

    steps:
      - name: Print
        run: |
          echo "Deploy hostnames: ${{ vars.DEPLOY_HOSTNAMES }}"

      - id: matrix
        run: |
          echo "value={"hostname$(echo '${{ vars.DEPLOY_HOSTNAMES}}' | sed 's/\"/\\\"/g')" >> $GITHUB_OUTPUT

  deploy:
    name: "Deploy"

    runs-on: ubuntu-latest

    needs: setup

    environment: ${{ inputs.environment }}

    strategy:
      matrix:
        hostname: ${{ fromJSON(needs.setup.outputs.matrix) }}

    steps:
      - name: Print
        run: |
          echo "Deploying to environment: ${{ inputs.environment }} on host: ${{ matrix.hostname }}"
